import { readFileSync, writeFileSync, cpSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { runInNewContext } from 'node:vm';

const root = resolve(process.argv[2] || '../on-tap');
const output = new URL('../public/', import.meta.url);
const context = { window: {} };
const files = ['index', 'cea201', 'mae101', 'mae101-fe', 'prf192', 'prf193', 'ssa101', 'sdi101m'];
const hashes = {};
for (const file of files) {
  const source = readFileSync(resolve(root, `subjects/${file}.js`), 'utf8');
  hashes[`${file}.js`] = createHash('sha256').update(source).digest('hex');
  runInNewContext(source, context, { filename: file, timeout: 1000 });
}
const courses = {}, quizzes = {}, counts = {};
for (const subject of context.window.SUBJECTS.filter(s => s.ready)) {
  const data = context.window.SUBJECT_DATA[subject.id];
  if (!data?.chapters || !Array.isArray(data.questions) || data.questions.length !== subject.count) throw Error(`Sai số lượng ${subject.code}`);
  const ids = new Set();
  quizzes[subject.code] = data.questions.map(q => {
    if (!Number.isSafeInteger(q.id) || q.id < 1 || ids.has(q.id) || !data.chapters[q.ch]) throw Error(`Sai ID/chương ${subject.code}:${q.id}`);
    ids.add(q.id);
    const indices = letters => letters.map(letter => {
      const index = letter.charCodeAt(0) - 65;
      if (!/^[A-F]$/.test(letter) || index >= q.opts.length) throw Error(`Sai đáp án ${subject.code}:${q.id}`);
      return index;
    });
    if (!Array.isArray(q.opts) || q.opts.length < 2 || q.opts.length > 6 || !q.ans?.length) throw Error('Sai lựa chọn');
    const correct = indices(q.ans), alternativeAnswers = indices(q.disputed || []);
    if (new Set(correct).size !== correct.length) throw Error('Trùng đáp án');
    for (const value of [q.q, ...q.opts.map(o => o || "[Lựa chọn trống trong nguồn]"), q.exp]) {
      if (typeof value !== 'string' || !value.trim()) throw Error('Thiếu nội dung');
      for (const match of value.matchAll(/<img\b[^>]*src="([^"]+)"/g)) {
        if (!/^mae101\/[\w/.-]+\.(svg|png)$/.test(match[1]) || match[1].includes('..') || !existsSync(resolve(root, 'subjects', match[1]))) throw Error(`Thiếu ảnh ${match[1]}`);
      }
    }
    const chapter = data.chapters[q.ch];
    return { q: q.q, o: q.opts.map(o => o || "[Lựa chọn trống trong nguồn]"), a: correct.length === 1 ? correct[0] : correct, e: q.exp,
      s: `On Tap ${subject.code}, câu ${q.id}`, chapter: chapter.short === chapter.name ? chapter.name : `${chapter.short}: ${chapter.name}`,
      topic: q.topic || '', sourceId: q.id, source: 'on-tap', richText: true, math: !!subject.math,
      ...(alternativeAnswers.length ? { alternativeAnswers } : {}) };
  });
  counts[subject.code] = quizzes[subject.code].length;
  if (['PRF192', 'SSA101'].includes(subject.code)) {
    courses[subject.code] = { name: subject.name, en: subject.name, accent: subject.id === 'prf192' ? '#785ac6' : '#ae791e',
      scope: subject.description, sourceNote: 'Ngân hàng câu hỏi và lời giải từ repo chenbaode/on-tap. Các mục dưới đây là chỉ mục ôn tập theo chương của nguồn.',
      sourceLink: `https://on-tap.pages.dev/quiz?s=${subject.id}`,
      groups: [{ name: 'Chương ôn tập từ On Tap', items: Object.entries(data.chapters).filter(([id]) => data.questions.some(q => String(q.ch) === id)).map(([id,ch]) => ({
        title: ch.name, idea: ch.blurb || `Ôn tập ${ch.name} qua ngân hàng câu hỏi On Tap.`,
        details: ch.blurb || 'Chọn tab Kiểm tra nhanh, sau đó chọn chương tương ứng để làm bài và xem lời giải.',
        key: `${data.questions.filter(q => String(q.ch) === id).length} câu hỏi có đáp án và lời giải.`,
        example: 'Làm bài tại tab Kiểm tra nhanh; lời giải hiện sau khi trả lời.', source: `On Tap ${subject.code} · ${ch.name}`
      })) }] };
  }
}
const revision = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], {encoding:'utf8'}).trim();
const manifest = { repository: 'chenbaode/on-tap', revision, hashes, counts };
const script = `// Generated by scripts/import-on-tap.mjs. Source commit: ${revision}\nwindow.ON_TAP_SYNC = ${JSON.stringify(manifest)};\nObject.assign(window.COURSES, ${JSON.stringify(courses)});\nfor (const [code, imported] of Object.entries(${JSON.stringify(quizzes)})) {\n  const existing = window.QUIZZES[code] || [];\n  window.QUIZZES[code] = existing.filter(q => q.source !== 'on-tap' && !/^On Tap /.test(q.s || '')).concat(imported);\n}\n`;
mkdirSync(new URL('on-tap/', output), {recursive:true});
cpSync(resolve(root, 'subjects/mae101'), new URL('on-tap/mae101', output), {recursive:true});
writeFileSync(new URL('on-tap-sync.js', output), script);
writeFileSync(new URL('on-tap-manifest.json', output), JSON.stringify(manifest,null,2)+'\n');
console.log({ revision, counts, total: Object.values(counts).reduce((a,b)=>a+b,0) });
